import { defineConfig } from "tsup";

export default defineConfig({
  entry: [
    "src/index.ts",
    "src/runtime/index.ts",
    "src/backtest/index.ts",
    "src/quant/index.ts",
    "src/validation/index.ts",
    "src/cli/index.ts",
    "src/viem/index.ts",
    "src/x402/index.ts",
    "src/mpp/index.ts",
    "src/wallet/index.ts",
    "src/wallet/browser.ts",
    "src/ai/index.ts",
    "src/store/index.ts",
    "src/adapters/hyperliquid/index.ts",
    "src/adapters/hyperliquid/browser.ts",
    "src/adapters/news/index.ts",
    "src/adapters/polymarket/index.ts",
  ],
  format: ["esm"],
  dts: true,
  sourcemap: true,
  clean: true,
  splitting: false,
  treeshake: true,
  outDir: "dist",
  shims: false,
  skipNodeModulesBundle: true,
});
